#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

usage(){
echo "$0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
}

if [ "$#" -ne 4 ]; then
usage()
fi

IP=$2
PATH_TO_FILE=$1
USERNAME=$3
PATH_TO_SSH_KEY=$4
scp -i "$PATH_TO_SSH_KEY" -o StrictHostkeyChecking=no "$IP" "$USERNAME" "$PATH_TO_FILE"
