#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

usage(){
echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
}

if [ "$#" -lt 3 ]; then
usage
fi

IP=$2
PATH_TO_FILE=$1
USERNAME=$3
PATH_TO_SSH_KEY=$4
scp -i "$PATH_TO_SSH_KEY" -o StrictHostkeyChecking=no  "$USERNAME@$IP:~/" "$PATH_TO_FILE"
