#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server.

usage(){
echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
exit 1
}

IP=$2
PATH_TO_FILE=$1
USERNAME=$3
PATH_TO_SSH_KEY=$4
if [ "$#" -eq 4 ];then 
	scp -o StrictHostkeyChecking=no -i "$PATH_TO_SSH_KEY"  "$USERNAME@$IP:~/" "$PATH_TO_FILE"
else
	usage
fi
