#!/usr/bin/env bash
#this script install a web server called nginx on a server
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx 
echo "Hello World!" >/var/www/html/index.nginx-debian.html
sudo service nginx start

