#!/usr/bin/env bash
#this script install a web server called nginx on a server

sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Backup the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

sudo nginx -t

sudo service nginx restart
