#!/usr/bin/env bash
#this script install a web server called nginx on a server

sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '/^}$/i \
    # 301 redirect for /redirect_me \
    location = /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    }' /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
