#!/usr/bin/env bash
# A Bash script that displays a list of currently running processes.
# shellcheck disable=SC2009

# Display lines containing the word "bash" to get the PID of the Bash process
ps aux | grep bash
