#!/usr/bin/env bash
#this script stops 4-to_infinty_and_beyond script

# Find the process ID (PID) of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -z "$pid" ]; then
	exit 
	#echo "Process '4-to_infinity_and_beyond' is not running."
else
    # Send SIGTERM signal to gracefully stop the process
    kill $pid

    # Check if the process is still running after sending SIGTERM
    sleep 2
    if ps -p $pid > /dev/null; then
        # If the process is still running, send SIGKILL to forcefully terminate it
        kill -9 $pid
     #   echo "Process '4-to_infinity_and_beyond' killed forcefully."
    #else
        #echo "Process '4-to_infinity_and_beyond' stopped gracefully."
    fi
fi

