#!/usr/bin/env bash
#this script stops another script "4-to-infinty_and_beyond"

# Find the process ID (PID) of the "4-to_infinity_and_beyond" process
#`pid=$(pgrep -f "4-to_infinity_and_beyond")
#
# Check if the process is running
#if [ -z "$pid" ]; then
#
#	exit
#else
# Use the SIGINT signal (Ctrl+C) to stop the process
#	kill -SIGINT $pid
#fi
# Find the process ID (PID) of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -z "$pid" ]; then
	pkill -INT -f "4-to_infinity_and_beyond"
   # echo "Process '4-to_infinity_and_beyond' is not running."
#else
    # Use the SIGINT signal (Ctrl+C) to stop the process
   # kill -SIGINT "$pid"
#    echo "Process '4-to_infinity_and_beyond' stopped gracefully."
fi

