#!/usr/bin/env bash
#    write a Bash script that accepts one argument
#    the script should run the whoami command under the user passed as an argument
#    make sure to try your script by passing different users
if [ $# -ne 0 ];then
	echo $1
else
	whoami
fi
